### ISSUE TITLE
deployed WAR file to tomcat: **java.lang.IllegalArgumentException: No implementation of method: :on-close of protocol: #'org.httpkit.server/Channel found for class: nil

### ISSUE THREAD

**Issue by shaulid** [ptaoussanis/sente#199]
Hi, 

I don't know whether my comment as seen in this old issue was seen :https://github.com/ptaoussanis/sente/issues/93

I have the same exception as in there:
**java.lang.IllegalArgumentException: No implementation of method: :on-close of protocol: #'org.httpkit.server/Channel found for class: nil
**
I am using http-kit with sente.
I am deploying a WAR file to openshift tomcat cartridge, which I created using lein-ring:
using the command:
lein uberwar.
I copy it to /webapps dir as ROOT.war and the WAR file is loaded OK and my webapp is loaded OK.

The exception occurs at this line:
(GET  "/chsk" req (ring-ajax-get-or-ws-handshake req))
- as in the Sente examples.

The exception does NOT happen when I don't use a WAR file and just run it locally using:
lein run

The line at sente.clj where  the exception occurs:
	at taoensso.sente$make_channel_socket_server_BANG_$fn__14770.invoke(sente.clj:482)

I cannot see the line in the file sente.clj in github because I guess it's created using cljx, so I cannot know exactly which line causes the exception.

Thanks for the help.

------------------------------------------------------------------------------------
Full exception:

java.lang.IllegalArgumentException: No implementation of method: :on-close of protocol: #'org.httpkit.server/Channel found for class: nil
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:554)
	at org.httpkit.server$eval15237$fn__15294$G__15228__15301.invoke(server.clj:36)
	at taoensso.sente.server_adapters.http_kit.HttpKitServerChanAdapter.ring_req__GT_server_ch_resp(http_kit.clj:22)
	at taoensso.sente$make_channel_socket_server_BANG_$fn__14770.invoke(sente.clj:482)
	at crmizer.handler$fn__15531.invoke(handler.clj:234)
	at compojure.core$make_route$fn__1805.invoke(core.clj:130)
	at compojure.core$wrap_route_middleware$fn__1801.invoke(core.clj:118)
	at compojure.core$if_route$fn__1773.invoke(core.clj:41)
	at compojure.core$if_method$fn__1765.invoke(core.clj:27)
	at compojure.core$routing$fn__1812.invoke(core.clj:144)
	at clojure.core$some.invoke(core.clj:2570)
	at compojure.core$routing.doInvoke(core.clj:144)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:632)
	at compojure.core$routes$fn__1816.invoke(core.clj:149)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__2060.invoke(keyword_params.clj:35)
	at ring.middleware.params$wrap_params$fn__2026.invoke(params.clj:64)
	at prone.middleware$wrap_exceptions$fn__4652.invoke(middleware.clj:81)
	at ring.middleware.reload$wrap_reload$fn__4482.invoke(reload.clj:22)
	at ring.middleware.anti_forgery$wrap_anti_forgery$fn__3277.invoke(anti_forgery.clj:90)
	at ring.middleware.flash$wrap_flash$fn__3170.invoke(flash.clj:35)
	at ring.middleware.session$wrap_session$fn__3150.invoke(session.clj:102)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__2060.invoke(keyword_params.clj:35)
	at ring.middleware.nested_params$wrap_nested_params$fn__2110.invoke(nested_params.clj:84)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__2153.invoke(multipart_params.clj:117)
	at ring.middleware.params$wrap_params$fn__2026.invoke(params.clj:64)
	at ring.middleware.cookies$wrap_cookies$fn__3023.invoke(cookies.clj:161)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__3429.invoke(absolute_redirects.clj:36)
	at ring.middleware.resource$wrap_resource$fn__3317.invoke(resource.clj:28)
	at ring.middleware.content_type$wrap_content_type$fn__3386.invoke(content_type.clj:30)
	at ring.middleware.default_charset$wrap_default_charset$fn__3406.invoke(default_charset.clj:26)
	at ring.middleware.not_modified$wrap_not_modified$fn__3367.invoke(not_modified.clj:52)
	at ring.middleware.x_headers$wrap_xss_protection$fn__3215.invoke(x_headers.clj:71)
	at ring.middleware.x_headers$wrap_frame_options$fn__3203.invoke(x_headers.clj:38)
	at ring.middleware.x_headers$wrap_content_type_options$fn__3209.invoke(x_headers.clj:53)
	at clojure.lang.Var.invoke(Var.java:379)
	at crmizer.listener$_contextInitialized$fn__11.invoke(listener.clj:1)
	at ring.util.servlet$make_service_method$fn__15602.invoke(servlet.clj:129)
	at crmizer.servlet$_service.invoke(servlet.clj:1)
	at crmizer.servlet.service(Unknown Source)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:652)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:745)

**Comment by shaulid** [comment]
It seems that the problem arises when the cljs client sents a websocket request to the server, this request returns this:

HTTP Status 500 - project.clj (No such file or directory)

type Exception report

message project.clj (No such file or directory)

description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.io.FileNotFoundException: project.clj (No such file or directory)
	java.io.FileInputStream.open(Native Method)
	java.io.FileInputStream.<init>(FileInputStream.java:146)
	clojure.java.io$fn__9189.invoke(io.clj:229)
	clojure.java.io$fn__9102$G__9095__9109.invoke(io.clj:69)
	clojure.java.io$fn__9201.invoke(io.clj:258)
	clojure.java.io$fn__9102$G__9095__9109.invoke(io.clj:69)
	clojure.java.io$fn__9163.invoke(io.clj:165)
	clojure.java.io$fn__9115$G__9091__9122.invoke(io.clj:69)
.
.
.

(still investigating)

**Comment by shaulid** [comment]
OK, so I took out everything related to sente from my project, and the problem persists.
So I apologize, it's not related to sente. It's related to deploying http-kit on tomcat.

**Comment by ptaoussanis** [comment]
No problem, I appreciate the update.
