### ISSUE TITLE
ring.middleware.session fails to process the Deferred response from Aleph sch adapter

### ISSUE THREAD

**Issue by dimovich** [ptaoussanis/sente#345]
Sente's adapter for Aleph will return a `Deferred` response during connection upgrade.
https://github.com/ptaoussanis/sente/blob/master/src/taoensso/sente/server_adapters/aleph.clj#L33

This `Deferred` response breaks the `wrap-session` middleware, which expects a hash map.
https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/session.clj#L45

My middleware stack:

``` clojure
(-> handler
    ring.middleware.session/wrap-session
    ring.middleware.anti-forgery/wrap-anti-forgery
    reitit.ring.middleware.muuntaja/format-middleware
    ring.middleware.keyword-params/wrap-keyword-params
    ring.middleware.params/wrap-params
    ring.middleware.gzip/wrap-gzip)
```

Would appreciate any feedback!

The stacktrace during connection upgrade:

```
SEVERE: error in HTTP handler
java.lang.IllegalArgumentException: contains? not supported on type: manifold.deferred.Deferred
	at clojure.lang.RT.contains(RT.java:853)
	at clojure.core$contains_QMARK_.invokeStatic(core.clj:1492)
	at clojure.core$contains_QMARK_.invoke(core.clj:1484)
	at ring.middleware.session$bare_session_response.invokeStatic(session.clj:45)
	at ring.middleware.session$bare_session_response.invoke(session.clj:43)
	at ring.middleware.session$session_response.invokeStatic(session.clj:74)
	at ring.middleware.session$session_response.invoke(session.clj:66)
	at ring.middleware.session$wrap_session$fn__24706.invoke(session.clj:109)
	at muuntaja.middleware$wrap_format$fn__28018.invoke(middleware.clj:73)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__26934.invoke(keyword_params.clj:53)
	at ring.middleware.params$wrap_params$fn__26890.invoke(params.clj:67)
	at ring.middleware.gzip$wrap_gzip$fn__53208.invoke(gzip.clj:84)
	at reitit.ring$ring_handler$fn__26328.invoke(ring.cljc:292)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at roll.handler$default_handler.invokeStatic(handler.clj:73)
	at roll.handler$default_handler.invoke(handler.clj:71)
	at aleph.http.server$handle_request$fn__50747$f__45833__auto____50748.invoke(server.clj:158)
	at clojure.lang.AFn.run(AFn.java:22)
	at io.aleph.dirigiste.Executor$Worker$1.run(Executor.java:62)
	at manifold.executor$thread_factory$reify__45715$f__45716.invoke(executor.clj:44)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by g7s** [comment]
Hi! Why is this closed? Have you resolved the issue? I can't get it to work..

**Comment by dimovich** [comment]
@g7s Yes, there are two solutions to this.

The [first solution](https://gist.github.com/dimovich/3f9cd75a21e5073bffc703f2417b136d) wraps your ring-handler (which may return a Defered) in a manifold chain.

The [second solution](https://github.com/muhuk/aleph-middleware) is to use an Aleph compatible middleware.

The first solution worked fine for me. It takes advantage of the new [async ring handlers](https://www.booleanknot.com/blog/2016/07/15/asynchronous-ring.html).
