### ISSUE TITLE
java.lang.IllegalArgumentException: No implementation of method: :on-close of protocol: #'org.httpkit.server/Channel found for class: nil

### ISSUE THREAD

**Issue by endrebak** [ptaoussanis/sente#388]
I am having this issue I can't figure out. Do you have any clue what it might be or any hints for how to debug?

```
java.lang.IllegalArgumentException: No implementation of method: :on-close of protocol: #'org.httpkit.server/Channel found for class: nil
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
	at org.httpkit.server$eval19781$fn__19851$G__19772__19858.invoke(server.clj:96)
	at taoensso.sente.server_adapters.http_kit.HttpKitServerChanAdapter.ring_req__GT_server_ch_resp(http_kit.clj:25)
	at taoensso.sente$make_channel_socket_server_BANG_$fn__21615.invoke(sente.cljc:606)
	at muuntaja.middleware$wrap_params$fn__8119.invoke(middleware.clj:52)
	at muuntaja.middleware$wrap_format$fn__8123.invoke(middleware.clj:73)
	at everclear.middleware$wrap_formats$fn__9289.invoke(middleware.clj:41)
	at ring.middleware.anti_forgery$wrap_anti_forgery$fn__6955.invoke(anti_forgery.clj:94)
	at ring.middleware.params$wrap_params$fn__9021.invoke(params.clj:67)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__8807.invoke(keyword_params.clj:53)
	at reitit.ring$ring_handler$fn__24478.invoke(ring.cljc:326)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:384)
	at ring.middleware.reload$wrap_reload$fn__4448.invoke(reload.clj:39)
	at selmer.middleware$wrap_error_page$fn__4463.invoke(middleware.clj:18)
	at prone.middleware$wrap_exceptions$fn__4704.invoke(middleware.clj:159)
	at ring.middleware.flash$wrap_flash$fn__8160.invoke(flash.clj:39)
	at ring.middleware.session$wrap_session$fn__8605.invoke(session.clj:108)
	at ring.adapter.undertow.middleware.session$wrap_undertow_session$fn__8711.invoke(session.clj:88)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__8807.invoke(keyword_params.clj:53)
	at ring.middleware.nested_params$wrap_nested_params$fn__8865.invoke(nested_params.clj:89)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__8997.invoke(multipart_params.clj:171)
	at ring.middleware.params$wrap_params$fn__9021.invoke(params.clj:67)
	at ring.middleware.cookies$wrap_cookies$fn__8484.invoke(cookies.clj:214)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__9209.invoke(absolute_redirects.clj:47)
	at ring.middleware.resource$wrap_resource_prefer_resources$fn__9057.invoke(resource.clj:25)
	at ring.middleware.content_type$wrap_content_type$fn__9157.invoke(content_type.clj:34)
	at ring.middleware.default_charset$wrap_default_charset$fn__9181.invoke(default_charset.clj:31)
	at ring.middleware.not_modified$wrap_not_modified$fn__9123.invoke(not_modified.clj:61)
	at ring.middleware.x_headers$wrap_x_header$fn__8747.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__8747.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__8747.invoke(x_headers.clj:22)
	at everclear.middleware$wrap_internal_error$fn__9283.invoke(middleware.clj:20)
	at ring.adapter.undertow$undertow_handler$fn$reify__42283.handleRequest(undertow.clj:33)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:370)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

I get this error in the developer console:

```
sente.cljc:1045 WebSocket connection to 'ws://localhost:3000/chsk?client-id=1aff9efa-b158-4247-84f8-4b21936a9085&csrf-token=zmd0tN%2BySX0N%2F58zu%2FFAg%2BpLKnac5jbJGxWK8kPbx6uTYxqjjimzsf4C9%2B%2FZE%2BwkC2%2F8ppHEHT9tX9XO' failed: 
eval @ sente.cljc:1045
core.cljs:159 ERROR [taoensso.sente:1058] - WebSocket error: [object Event]
eval @ core.cljs:159

```

**Comment by endrebak** [comment]
If this is not related or the wrong place to ask, please feel free to close.
